### ISSUE TITLE
Undo message with gates involved does not work.

### ISSUE THREAD

**Issue by acampesino** [Ericsson/papyrus-patches#19]
The undo of creating a message with a gate throws an exception:

Caused by: java.lang.NullPointerException
	at org.eclipse.papyrus.uml.service.types.command.ConfigureMessageEventCommand.doUndo(ConfigureMessageEventCommand.java:357)
	at org.eclipse.emf.workspace.AbstractEMFOperation.undo(AbstractEMFOperation.java:370)
	... 81 more

**Comment by acampesino** [comment]
Fixed in 49404b2
